// --- UI Text Data (Localization) ---
const globalTextData = {
    global: {
        en: {
            // General Status & UI
            "toggle_language_aria": "Switch language",
            "system_status_online_short": "System Online",
            "system_processing_short": "Processing...",
            "status_ok": "Operational",
            "status_warning": "Caution",
            "status_danger": "Critical",
            "status_error": "System Fault",
            "unknown": "Unknown",
            "standby": "Standby",
            "online": "Online",
            "offline": "Offline",
            "none": "None",
            "not_available_short": "N/A",
            "active": "Active",
            "failed": "Failure",
            "initializing": "Initializing...",
            "connecting": "Authenticating: {PLAYER_ID}",
            "error_saving_progress": "System: Error saving game progress.",
            "error_reconstruct_story": "Error: Could not reconstruct part of the story.",
            "error_load_prompt_file": "SYSTEM ERROR: Could not load prompt: {THEME}/{PROMPT_NAME}.",
            "error_no_prompts_for_theme":"SYSTEM ERROR: Prompts for theme \"{THEME}\" are not configured.",
            "error_api_call_failed":"SYSTEM ERROR: {ERROR_MSG}",
            "alert_identifier_required": "Please enter your identifier (name/name).",
            "error_session_init_failed": "Failed to initialize session. Please check panel and try again.",
            "error_load_prompts_critical": "CRITICAL: Essential game prompts for theme \"{THEME}\" failed to load. Cannot continue.",
            "error_resume_failed_prompts": "Error resuming session: Failed to load essential prompts for theme {THEME}.",
            "error_dashboard_config_missing": "Error: Dashboard configuration is missing for this theme.",
            "error_critical_manifest_missing": "CRITICAL: Theme manifest (themes-manifest.js) is missing or empty. Application cannot start.",
            "error_initial_theme_data_load_failed": "Error: Failed to load initial data for one or more themes. Some themes may not be available.",
            "error_theme_data_load_failed": "Error: Failed to load required data for theme {THEME_ID}. This theme cannot be started.",

            // Buttons & Actions
            "button_new_game": "New Game",
            "aria_label_new_game": "Start a new game",
            "close_theme_button_aria_label": "Close {THEME_NAME} session",
            "theme_icon_alt_text_playing": "Playing",
            "theme_icon_alt_text_liked": "Favorite",
            "placeholder_name_login": "Enter Identifier...",
            "placeholder_command": "Enter action...",
            "button_access_systems": "Begin",
            "button_execute_command": "Execute",
            "coming_soon_button": "Coming Soon",
            "prompt_enter_api_key_title": "API Key Required",
            "placeholder_api_key_input": "Enter your Gemini API Key here",
            "alert_title_error": "Error",
            "alert_title_notice": "Notice",
            "confirm_new_game_title": "Confirm New Game",

            // Modal
            "modal_ok_button": "OK",
            "modal_confirm_button": "Confirm",
            "modal_cancel_button": "Cancel",
            "modal_yes_button": "Yes",
            "modal_no_button": "No",
            "modal_default_title_alert": "Alert",
            "modal_default_title_confirm": "Confirmation",
            "modal_default_title_prompt": "Input Required",

            // Confirmations & Alerts
            "confirm_new_game_generic": "Start new game in {THEME_NAME}? Progress in this theme will be lost.",
            "alert_api_key_required":"Gemini API Key is required. Please refresh and provide a key.",
            "prompt_enter_api_key": "Welcome! Please enter your Google Gemini API Key:",
            "error_critical_no_api_key":"CRITICAL: Gemini API Key not provided. Application cannot connect to AI.",
            "alert_level_1_display_default": "Condition Nominal",
            "alert_level_2_display_default": "Condition Elevated",
            "alert_level_3_display_default": "Condition High",
            "alert_level_4_display_default": "Condition Critical",

            // Model Toggle
            "label_toggle_model": "AI Model",
            "aria_label_toggle_model_generic": "Toggle AI Model",
            "button_toggle_to_free": "Use Free Model",
            "button_toggle_to_paid": "Use Paid Model",
            "aria_label_current_model_paid": "Currently using Paid AI Model. Switch to Free Model.",
            "aria_label_current_model_free": "Currently using Free AI Model. Switch to Paid Model.",
            "system_model_set_paid": "System: Switched to Paid AI Model ({MODEL_NAME}).",
            "system_model_set_free": "System: Switched to Free AI Model ({MODEL_NAME}).",

            // Language & System Messages
            "system_lang_set_en": "System: UI & Narrative set to ENGLISH.",
            "system_lang_set_cs": "System: UI & Narrative set to CZECH.",
            "system_session_resumed": "Welcome back, {PLAYER_ID}! Session resumed for {THEME_NAME}.",
            "system_theme_set_generic": "System: {THEME_NAME} scenario activated.",
            "system_new_game_initiated": "System: New {THEME_NAME} game sequence initiated.",

            // Login & Registration
            "button_login": "Login",
            "aria_label_login": "Log into your account",
            "button_register": "Register",
            "aria_label_register": "Create a new account",
            "button_logout": "Logout",
            "aria_label_logout": "Log out of your account",
            "button_user_profile": "Profile",
            "aria_label_user_profile": "View your profile",

            "modal_title_login": "Login to Anomady",
            "modal_title_register": "Create Anomady Account",
            "label_email": "Email Address",
            "placeholder_email": "your@email.com",
            "label_password": "Password",
            "placeholder_password": "Enter your password",
            "placeholder_password_register": "Choose a strong password (min. 8 chars)",

            "alert_registration_success_title": "Registration Successful",
            "alert_registration_success_message": "Your account has been created! Please log in to continue.",
            "alert_login_failed_title": "Login Failed",
            "alert_invalid_email_format": "Please enter a valid email address.",
            "alert_fill_required_fields": "Please fill in all required fields.",
            "error_api_call_failed": "Operation failed: {ERROR_MSG}",

            "system_logged_out": "System: You have been logged out.",
            "system_session_restored": "System: Welcome back, {USER_EMAIL}! Your session has been restored.",
            "system_token_expired_logged_out": "System: Your session has expired. Please log in again.",
            "modal_switch_to_register": "Don't have an account? Register",
            "modal_switch_to_login": "Already have an account? Login",
            "modal_title_user_profile": "User Profile",
            "label_profile_email": "Email:",
            "label_profile_joined_date": "Joined:",
            "label_profile_app_language": "App Language:",
            "label_profile_narrative_language": "Narrative Language:",
            "label_profile_model_preference": "AI Model:",
            "button_profile_logout": "Logout",
            "button_profile_change_password": "Change Password",
            "text_password_change_soon": "(Password change coming soon)",
            "label_profile_preferences_title": "Preferences",
            "modal_title_change_password": "Change Password",
            "label_current_password": "Current Password",
            "placeholder_current_password": "Enter your current password",
            "label_new_password": "New Password",
            "placeholder_new_password": "Enter your new password (min. 8 chars)",
            "label_confirm_new_password": "Confirm New Password",
            "placeholder_confirm_new_password": "Re-enter your new password",
            "alert_password_change_success_title": "Password Changed",
            "alert_password_change_success_message": "Your password has been successfully updated.",
            "alert_passwords_do_not_match": "New passwords do not match. Please try again.",
            "alert_new_password_too_short": "New password must be at least 8 characters long.",
            "alert_new_password_same_as_old": "New password cannot be the same as the current password.",
        },
        cs: {
            // General Status & UI
            "toggle_language_aria": "Přepnout jazyk",
            "system_status_online_short": "Systém Online",
            "system_processing_short": "Zpracovávám...",
            "status_ok": "V provozu",
            "status_warning": "Pozor",
            "status_danger": "Kritické",
            "status_error": "Chyba systému",
            "unknown": "Neznámý",
            "standby": "Pohotovost",
            "online": "Online",
            "offline": "Offline",
            "none": "Žádný",
            "not_available_short": "N/A",
            "active": "Aktivní",
            "failed": "Selhání",
            "initializing": "Inicializuji...",
            "connecting": "Ověřuji totožnost: {PLAYER_ID}",
            "error_saving_progress": "Systém: Chyba při ukládání postupu hry.",
            "error_reconstruct_story": "Chyba: Nelze rekonstruovat část příběhu.",
            "error_load_prompt_file": "SYSTÉMOVÁ CHYBA: Nelze načíst skript: {THEME}/{PROMPT_NAME}.",
            "error_no_prompts_for_theme":"SYSTÉMOVÁ CHYBA: Skripty pro téma \"{THEME}\" nejsou nakonfigurovány.",
            "error_api_call_failed":"SYSTÉMOVÁ CHYBA: {ERROR_MSG}",
            "alert_identifier_required": "Zadejte prosím svůj identifikátor (jméno/volací znak).",
            "error_session_init_failed": "Nepodařilo se inicializovat relaci. Zkontrolujte konzoli a zkuste to znovu.",
            "error_load_prompts_critical": "KRITICKÉ: Nepodařilo se načíst základní herní skripty pro téma \"{THEME}\". Nelze pokračovat.",
            "error_resume_failed_prompts": "Chyba obnovení relace: Nepodařilo se načíst základní skripty pro téma {THEME}.",
            "error_dashboard_config_missing": "Chyba: Chybí konfigurace panelu pro toto téma.",
            "error_critical_manifest_missing": "KRITICKÉ: Manifest témat (themes-manifest.js) chybí nebo je prázdný. Aplikaci nelze spustit.",
            "error_initial_theme_data_load_failed": "Chyba: Nepodařilo se načíst počáteční data pro jedno či více témat. Některá témata nemusí být dostupná.",
            "error_theme_data_load_failed": "Chyba: Nepodařilo se načíst požadovaná data pro téma {THEME_ID}. Toto téma nelze spustit.",

            // Buttons & Actions
            "button_new_game": "Nová Hra",
            "aria_label_new_game": "Začít novou hru",
            "close_theme_button_aria_label": "Zavřít relaci {THEME_NAME}",
            "theme_icon_alt_text_playing": "Hraje se",
            "theme_icon_alt_text_liked": "Oblíbené",
            "placeholder_name_login": "Zadejte identifikátor...",
            "placeholder_command": "Zadejte akci...",
            "button_access_systems": "Spustit",
            "button_execute_command": "Provést",
            "coming_soon_button": "Již Brzy",
            "prompt_enter_api_key_title": "Vyžadován API Klíč",
            "placeholder_api_key_input": "Zadejte svůj Gemini API Klíč",
            "alert_title_error": "Chyba",
            "alert_title_notice": "Upozornění",
            "confirm_new_game_title": "Potvrdit Novou Hru",

            // Modal
            "modal_ok_button": "OK",
            "modal_confirm_button": "Potvrdit",
            "modal_cancel_button": "Zrušit",
            "modal_yes_button": "Ano",
            "modal_no_button": "Ne",
            "modal_default_title_alert": "Upozornění",
            "modal_default_title_confirm": "Potvrzení",
            "modal_default_title_prompt": "Vyžadován vstup",

            // Confirmations & Alerts
            "confirm_new_game_generic": "Začít novou hru v {THEME_NAME}? Postup v tomto tématu bude ztracen.",
            "alert_api_key_required":"Je vyžadován Gemini API klíč. Obnovte stránku a zadejte klíč.",
            "prompt_enter_api_key": "Vítejte! Zadejte prosím svůj Google Gemini API klíč:",
            "error_critical_no_api_key":"KRITICKÉ: Gemini API klíč nebyl zadán. Aplikace se nemůže připojit k AI.",
            "alert_level_1_display_default": "Stav Nominální",
            "alert_level_2_display_default": "Stav Zvýšený",
            "alert_level_3_display_default": "Stav Vysoký",
            "alert_level_4_display_default": "Stav Kritický",

            // Model Toggle
            "label_toggle_model": "AI Model",
            "aria_label_toggle_model_generic": "Přepnout AI Model",
            "button_toggle_to_free": "Použít Model Zdarma",
            "button_toggle_to_paid": "Použít Placený Model",
            "aria_label_current_model_paid": "Používáte Placený AI Model. Přepnout na Model Zdarma.",
            "aria_label_current_model_free": "Používáte Model Zdarma. Přepnout na Placený Model.",
            "system_model_set_paid": "Systém: Přepnuto na Placený AI Model ({MODEL_NAME}).",
            "system_model_set_free": "Systém: Přepnuto na Model Zdarma ({MODEL_NAME}).",

            // Language & System Messages
            "system_lang_set_en": "Systém: UI a Příběh nastaveny na ANGLIČTINU.",
            "system_lang_set_cs": "Systém: UI a Příběh nastaveny na ČEŠTINU.",
            "system_session_resumed": "Vítejte zpět, {PLAYER_ID}! Relace obnovena pro {THEME_NAME}.",
            "system_theme_set_generic": "Systém: Scénář {THEME_NAME} aktivován.",
            "system_new_game_initiated": "Systém: Zahájena sekvence nové hry ({THEME_NAME}).",

            // Login & Registration
            "button_login": "Přihlásit se",
            "aria_label_login": "Přihlásit se k vašemu účtu",
            "button_register": "Registrovat",
            "aria_label_register": "Vytvořit nový účet",
            "button_logout": "Odhlásit se",
            "aria_label_logout": "Odhlásit se z vašeho účtu",
            "button_user_profile": "Profil",
            "aria_label_user_profile": "Zobrazit váš profil",

            "modal_title_login": "Přihlášení do Anomady",
            "modal_title_register": "Vytvořit Anomady Účet",
            "label_email": "E-mailová Adresa",
            "placeholder_email": "vas@email.cz",
            "label_password": "Heslo",
            "placeholder_password": "Zadejte své heslo",
            "placeholder_password_register": "Zvolte silné heslo (min. 8 znaků)",

            "alert_registration_success_title": "Registrace Úspěšná",
            "alert_registration_success_message": "Váš účet byl vytvořen! Prosím, přihlaste se pro pokračování.",
            "alert_login_failed_title": "Přihlášení Selhalo",
            "alert_invalid_email_format": "Zadejte prosím platnou e-mailovou adresu.",
            "alert_fill_required_fields": "Vyplňte prosím všechna povinná pole.",
            "error_api_call_failed": "Operace selhala: {ERROR_MSG}",

            "system_logged_out": "Systém: Byli jste odhlášeni.",
            "system_session_restored": "Systém: Vítejte zpět, {USER_EMAIL}! Vaše relace byla obnovena.",
            "system_token_expired_logged_out": "Systém: Platnost vaší relace vypršela. Přihlaste se prosím znovu.",
            "modal_switch_to_register": "Nemáte účet? Registrovat se",
            "modal_switch_to_login": "Již máte účet? Přihlásit se",
            "modal_title_user_profile": "Uživatelský Profil",
            "label_profile_email": "E-mail:",
            "label_profile_joined_date": "Registrován:",
            "label_profile_app_language": "Jazyk Aplikace:",
            "label_profile_narrative_language": "Jazyk Příběhu:",
            "label_profile_model_preference": "Model AI:",
            "button_profile_logout": "Odhlásit se",
            "button_profile_change_password": "Změnit Heslo",
            "text_password_change_soon": "(Změna hesla bude brzy dostupná)",
            "label_profile_preferences_title": "Předvolby",
            "modal_title_change_password": "Změnit Heslo",
            "label_current_password": "Současné Heslo",
            "placeholder_current_password": "Zadejte své současné heslo",
            "label_new_password": "Nové Heslo",
            "placeholder_new_password": "Zadejte nové heslo (min. 8 znaků)",
            "label_confirm_new_password": "Potvrdit Nové Heslo",
            "placeholder_confirm_new_password": "Zadejte znovu nové heslo",
            "alert_password_change_success_title": "Heslo Změněno",
            "alert_password_change_success_message": "Vaše heslo bylo úspěšně aktualizováno.",
            "alert_passwords_do_not_match": "Nová hesla se neshodují. Zkuste to prosím znovu.",
            "alert_new_password_too_short": "Nové heslo musí mít alespoň 8 znaků.",
            "alert_new_password_same_as_old": "Nové heslo nemůže být stejné jako současné heslo.",
        }
    },
    landing: {
        en: {
            // Generic Landing Page UI
            "landing_theme_description_title": "World Lore",
            "landing_theme_info_title": "Scenario Briefing",
            "landing_select_theme_prompt_lore": "Select a scenario from the grid to view its background.",
            "landing_select_theme_prompt_details": "Select a scenario to view its parameters and objectives.",
            "landing_theme_name_label": "Name",
            "landing_theme_inspiration_label": "Inspiration",
            "landing_theme_tone_label": "Tone",
            "landing_theme_concept_label": "Core Concept",
            "landing_choose_theme_button": "Engage This Scenario",
            "alert_select_theme_first": "Please select a theme scenario from the grid first.",
            "aria_label_like_theme": "Add to Favorites",
            "aria_label_unlike_theme": "Remove from Favorites",
            "toggle_language": "English"
        },
        cs: {
            // Generic Landing Page UI
            "landing_theme_description_title": "Dějiny světa",
            "landing_theme_info_title": "Přehled Scénáře",
            "landing_select_theme_prompt_lore": "Vyberte scénář pro zobrazení jeho dějin.",
            "landing_select_theme_prompt_details": "Vyberte scénář pro zobrazení jeho parametrů a cílů.",
            "landing_theme_name_label": "Název",
            "landing_theme_inspiration_label": "Inspirace",
            "landing_theme_tone_label": "Tón",
            "landing_theme_concept_label": "Základní Koncept",
            "landing_choose_theme_button": "Spustit Scénář",
            "alert_select_theme_first": "Prosím, nejprve vyberte tématický scénář z mřížky.",
            "aria_label_like_theme": "Přidat k oblíbeným",
            "aria_label_unlike_theme": "Odebrat z oblíbených",
            "toggle_language": "Česky"
        }
    }
};
